#Example Asset Catalog Editing Script

# The # symbol indicates a comment, meaning anything written after it won't have any effect


#Load python modules, these allow for additional functionality
import os
import json
import csv

#Change these paths to where ever your asset library is installed
CATALOG_PATH = r"J:\REAssetLibrary\RE3RT\REAssetCatalog_RE3RT.tsv"
#Where to save the edited catalog to
#By default it doesn't overwrite the original, you can make it do that but you should make sure your code runs without errors first before changing it.
CATALOG_PATH_OUTPUT = r"J:\REAssetLibrary\RE3RT\REAssetCatalog_RE3RT_edited.tsv"

AUTOMATIC_CATEGORY_LIST = [
	#Change here

	#The entries in this list assign directories to specific categories
	#If a file path contains any part of second entry, it gets assigned to that category
	#The ordering of items in this list doesn't matter, files will always be checked if they match the most specific categories first (The longest ones in other words)
	
	
	#The r before the quotation marks indicates a raw string, this means that you don't need to worry about slashes or special characters causing issues
	
	#Copy and paste these entries for as many categories as you need.
	#Any categories that don't match to a directory won't be used.
	#Be sure to keep the indentation the same or you will get errors when the script is run.
	
	#Start the directory path from inside the natives/STM/ folder
	#Make sure the slashes are forward slashes /
	
	#(r"CATEGORY_NAME",r"directoryPath"),
	("Weapons",r"escape/character/weapon"),
	("Characters/Carlos",r"escape/character/player/pl0000"),
	("Characters/Jill",r"escape/character/player/pl2000"),
	("Characters/Jill",r"escape/character/player/pl2910"),
	("Characters/Jill",r"escape/character/player/pl2920"),
	
	("Props",r"escape/setmodel"),
	("Props/Gimmicks",r"escape/setmodel/sm4x_gimmick"),
	("Items",r"escape/setmodel/sm7x_item"),
	
	("Stage Models",r"escape/environment/location"),
	("VFX",r"vfx/"),
	("VFX",r"escape/vfx/"),
	
	]


#-------------

AUTOMATIC_CATEGORY_LIST.sort(key = lambda item: len(item[1]))#Sort so largest strings are first
AUTOMATIC_CATEGORY_LIST.reverse()

OVERRIDE_DIR = "Overrides"#Load diffs generated by the blender addon inside the overrides folder

#Dictionary that stores a mapping of file paths to a container with names,category,etc.
overrideDict = dict()
if os.path.isdir(OVERRIDE_DIR):
	for entry in os.scandir(OVERRIDE_DIR):
		if entry.is_file() and entry.name.endswith(".tsv"):
			tsvPath = os.path.join(OVERRIDE_DIR,entry.name)
			with open(tsvPath,"r") as file:
				rd = csv.reader(file, delimiter="\t", quotechar='"')
				next(rd)#Skip header
				#Read each line in the override tsv file
				for row in rd:
					overrideDict[row[0]] = list(row)
				print(f"Loaded override file: {tsvPath}")
						
#Read the existing catalog
with open(CATALOG_PATH,"r") as file:
    lines = file.readlines()

with open(CATALOG_PATH_OUTPUT,"w") as outputFile:
	outputFile.write("File Path\tDisplay Name\tCategory (Forward Slash Separated)\tTags (Comma Separated)\tPlatform Extension\tLanguage Extension\n")#Write header line
	for line in lines[1:]:

		#If not a blank line
		if len(line.strip()) != 0:
			#Split the line into variables by separating by tab
			filePath,name,category,tags,platformExtension,langExtension = line.split("\t")
			
			#Category detection
			for categoryTuple in AUTOMATIC_CATEGORY_LIST:
				#If the file path contains any of the listed directory paths, assign it to that category
				if categoryTuple[1].lower() in filePath.lower():
					category = categoryTuple[0]
					#Once a category is found, theres no point in checking the rest of the categories so break stops it
					break
			
			#Get the file name and extension as variables
			splitext = os.path.splitext(os.path.split(filePath)[1])
			fileName = splitext[0]
			fileExtension = splitext[1]
			
			#Add additional logic here, you can load IDs from csv or json files and assign them to specfic files as an example
			
			
			#Name Overrides
			if filePath in overrideDict:
				override = overrideDict[filePath]
				name = override[1]
				category = override[2]
				tags = override[3]
			outputFile.write(f"{filePath}\t{name}\t{category}\t{tags}\t{platformExtension}\t{langExtension}")
print(f"Generated new catalog: {CATALOG_PATH_OUTPUT}")